import React, { useState } from 'react'
import { useLocation, useNavigate } from 'react-router-dom'
import { TrainFront } from 'lucide-react'
import { useAuth } from '../context/AuthContext'

export default function Login() {
  const { login } = useAuth(); const [username, setUsername] = useState(''); const [password, setPassword] = useState(''); const [remember, setRemember] = useState(false); const [error, setError] = useState(''); const navigate = useNavigate(); const location = useLocation()
  const finish = (user) => { const requested = location.state?.from?.pathname; const adminOnly = ['/alerts', '/hardware', '/ai', '/ai-detection', '/switching', '/tasks', '/workers', '/repair-history', '/sensor-history', '/simulation', '/model', '/settings'].some((path) => requested === path || requested?.startsWith(`${path}/`)); navigate(requested && (user.role === 'admin' || !adminOnly) ? requested : user.role === 'admin' ? '/admin' : '/worker', { replace: true }) }
  const submit = async (event) => { event.preventDefault(); setError(''); try { finish(await login({ username, password }, remember)) } catch { setError('Unable to sign in. Check your credentials or API connection.') } }
  const demoLogin = async (role) => { setError(''); try { finish(await login({ username: role, password: role }, false)) } catch { setError('Demo login unavailable. Start the mock server or use the real backend.') } }
  return <main className="login"><section className="login-card"><div className="brand-mark"><TrainFront size={30} /></div><p className="eyebrow">Railway monitoring system</p><h1>RailSafe</h1><p className="muted">Sign in to access your assigned operations view.</p><form onSubmit={submit}><label>Username<input value={username} onChange={(event) => setUsername(event.target.value)} placeholder="Enter username" autoComplete="username" required /></label><label>Password<input type="password" value={password} onChange={(event) => setPassword(event.target.value)} placeholder="Enter password" autoComplete="current-password" required /></label><label className="remember"><input type="checkbox" checked={remember} onChange={(event) => setRemember(event.target.checked)} />Remember me</label>{error && <p className="login-error" role="alert">{error}</p>}<button className="primary">Sign in</button></form>{import.meta.env.VITE_DEMO_AUTH === 'true' && <div className="demo-login"><small>Temporary local demo access</small><div><button type="button" onClick={() => demoLogin('admin')}>Demo Admin</button><button type="button" onClick={() => demoLogin('worker')}>Demo Worker</button></div></div>}<small>Backend authorization must validate the role on every endpoint.</small></section></main>
}
