import React, { useMemo, useState } from 'react'
import { Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import Header from '../components/Header'
import Panel from '../components/Panel'
import { EmptyState, ErrorState, LoadingState } from '../components/StateMessage'
import { useDevices, useSensorHistory } from '../hooks/useData'

const unwrap = (value) => value?.items ?? value?.data ?? value ?? []
const points = (data, field) => unwrap(data).map((item) => ({ time: item.timestamp || item.updated_at || 'NO DATA', value: item[field] ?? item.value?.[field] ?? item.reading?.[field] })).filter((item) => item.value !== undefined && item.value !== null)

export default function SensorHistory() { const [windowName, setWindowName] = useState('24h'); const devices = useDevices(); const device = (Array.isArray(devices.data) ? devices.data : [])[0]; const state = useSensorHistory(device?.id, windowName); const temperature = useMemo(() => points(state.data, 'temperature'), [state.data]); const vibration = useMemo(() => points(state.data, 'vibration'), [state.data]); return <><Header title="Sensor History" text="Stored temperature and vibration readings." /><div className="toolbar-row"><label>Window<select value={windowName} onChange={(event) => setWindowName(event.target.value)}><option value="1h">1 hour</option><option value="24h">24 hours</option><option value="7d">7 days</option></select></label></div>{state.loading ? <LoadingState>Loading sensor history...</LoadingState> : state.error ? <ErrorState /> : <div className="history-grid"><Panel title="Temperature" status={temperature.length ? `${temperature.length} readings` : 'NO DATA'}>{temperature.length ? <ResponsiveContainer width="100%" height={260}><LineChart data={temperature}><XAxis dataKey="time" hide /><YAxis width={42} /><Tooltip /><Line dataKey="value" stroke="var(--signal-amber)" dot={false} /></LineChart></ResponsiveContainer> : <EmptyState>No temperature readings</EmptyState>}</Panel><Panel title="Vibration" status={vibration.length ? `${vibration.length} readings` : 'NO DATA'}>{vibration.length ? <ResponsiveContainer width="100%" height={260}><LineChart data={vibration}><XAxis dataKey="time" hide /><YAxis width={42} /><Tooltip /><Line dataKey="value" stroke="var(--signal-blue-minor)" dot={false} /></LineChart></ResponsiveContainer> : <EmptyState>No vibration readings</EmptyState>}</Panel></div>}</> }
