import React, { useState } from 'react'
import Header from '../components/Header'
import Drawer from '../components/Drawer'
import Lamp from '../components/Lamp'
import { EmptyState, ErrorState, LoadingState } from '../components/StateMessage'
import { useAlerts, useTasks, useWorkers } from '../hooks/useData'
import { createTask } from '../services/api'

export default function Tasks() {
  const [status, setStatus] = useState(''); const [open, setOpen] = useState(false); const [alertId, setAlertId] = useState(''); const [workerId, setWorkerId] = useState(''); const [message, setMessage] = useState('')
  const tasksState = useTasks(); const alertsState = useAlerts({ status: 'ACKNOWLEDGED' }); const workersState = useWorkers(); const tasks = (Array.isArray(tasksState.data) ? tasksState.data : []).filter((task) => !status || task.status === status); const acknowledged = Array.isArray(alertsState.data) ? alertsState.data : []; const workers = Array.isArray(workersState.data) ? workersState.data : []
  const submit = async (event) => { event.preventDefault(); setMessage(''); try { await createTask({ alert_id: alertId, worker_id: workerId, status: 'ASSIGNED' }); setMessage('Task created.'); setOpen(false); tasksState.refresh() } catch { setMessage('Task creation failed.') } }
  return <><Header title="Tasks" text="Assign and monitor maintenance work." /><div className="toolbar-row"><label>Status<select value={status} onChange={(event) => setStatus(event.target.value)}><option value="">ALL</option><option>ASSIGNED</option><option>ACCEPTED</option><option>IN_PROGRESS</option><option>COMPLETED</option></select></label><button className="primary" onClick={() => setOpen(true)}>Assign Worker</button></div>{message && <p className="muted">{message}</p>}{tasksState.loading ? <LoadingState>Loading tasks...</LoadingState> : tasksState.error ? <ErrorState /> : tasks.length ? <div className="admin-list">{tasks.map((task) => <article className="admin-row" key={task.id}><Lamp severity={String(task.priority || task.severity || 'missing_data').toLowerCase()} label={task.priority || task.severity || 'NO DATA'} /><div><b>{task.defect || task.type || 'NO DATA'}</b><small className="data-line">{task.chainage || 'NO DATA'} · {task.worker_id || 'NO DATA'}</small></div><code>{task.status || 'NO DATA'}</code></article>)}</div> : <EmptyState>No tasks</EmptyState>}<Drawer open={open} title="Assign Worker" onClose={() => setOpen(false)}><form className="drawer-form" onSubmit={submit}><label>Acknowledged alert<select required value={alertId} onChange={(event) => setAlertId(event.target.value)}><option value="">Select alert</option>{acknowledged.map((alert) => <option key={alert.id} value={alert.id}>{alert.id} · {alert.defect || 'NO DATA'}</option>)}</select></label><label>Worker<select required value={workerId} onChange={(event) => setWorkerId(event.target.value)}><option value="">Select worker</option>{workers.map((worker) => <option key={worker.id || worker.worker_id} value={worker.id || worker.worker_id}>{worker.name || worker.id || 'NO DATA'}</option>)}</select></label><button className="primary" type="submit">Create task</button></form></Drawer></>
}
